### ISSUE TITLE
Add optional 'lineLength' prop

### ISSUE THREAD

**Issue by OmnesPotens** [quelchx/vue-writer#10]
**Is your feature request related to a problem? Please describe.**
When passing variable-lengthed strings to the vuewriter, its possible for there to be very long continuous lines.
This can lead to odd issues where the text bleeds into other elements or jarring "jumps" after particularly long lines are done being animated. 

Edit: It seems vuewriter treats strings with spaces differently than strings without spaces. Essentially, if a string without spaces is too long to fit within the constraints of the parent element of the vuewriter then it can and probably will overflow, but adding spaces to this string will enable it to constrain the string when reaching the contstraining width. 

**Describe the solution you'd like**
A new optional prop "lineLength" which would control the maximum number of characters that would be written before automatically inserting a linebreak/newline before continuing the writing animation.

**Describe alternatives you've considered**
Handle overflow properly when strings that **don't** contain spaces are too long for the constraining width, just like vuewriter currently does for strings that **do** contain spaces.

**Additional context**
Here is a screenshot attempting to show what I mean (the vuewriter string is on the left):
![image](https://user-images.githubusercontent.com/21691862/190964373-0e2c2158-d893-47c8-b0d9-cfe5d45490c3.png)

**Comment by quelchx** [comment]
With my current job position -- I am no longer able to maintain this project and post updates. I have been focused on other priorities right now and have no current plans for further feature development or improvements.

It will continue to be here on GitHub and we will still make critical updates (e.g. security fixes, if any) as required, but will not be actively monitoring or replying to issues and pull requests.
