### ISSUE TITLE
Caret not showing

### ISSUE THREAD

**Issue by sdezza** [quelchx/vue-writer#2]
**BUG**
The caret (cursor) is not showing

**Implementation Script**
`<VueWriter :array="['test','test2','test3','test4']" :typeSpeed="70" :eraseSpeed="50" :delay="1000" :caret="cursor" />`

**Script Inspect in Browser**
```
<div class="is-typed">
<span class="typed">test2</span>
<span class="cursor [object Object]">&nbsp;</span>
</div>
```

**Desktop:**
_Tested on Firefox & Chrome_
 - Microsoft Windows 10 Pro
 - Firefox
 - 95.0

 - Microsoft Windows 10 Pro
 - Chrome
 - Version 96.0.4664.110 (Official Build) (64-bit)
 
**Project dependencies**

  "dependencies": {
    "@popperjs/core": "^2.11.0",
    "bootstrap": "^5.1.3",
    "bootstrap-icons-vue": "^0.8.0",
    "core-js": "^3.6.5",
    "mapbox-gl": "^2.6.1",
    "vue": "^3.0.0",
    "vue-easy-lightbox": "^1.2.4",
    "vue-router": "^4.0.0-0",
    "vue-writer": "^1.1.2",
    "vuex": "^4.0.0-0"
  },

**Comment by quelchx** [comment]
The styling has been removed as a request. You will have to add styling yourself. Refer to the part of the documentation that shows a small but simple example of how to target specific classes and add a blinking caret animation. Hope this helps.
https://github.com/quelchx/vue-writer#styling

**Comment by sdezza** [comment]
Oops! The documentation is sufficiently clear. I omitted this part.

Thank you for this easy to use feature ;)
