### ISSUE TITLE
Not sure but I think some .d.ts file is needed in the dist folder as I'm not able to import this file

### ISSUE THREAD

**Issue by yatharthv8** [quelchx/vue-writer#3]
**Describe the bug**
Could not find a declaration file for module 'vue-writer'. 'd:/Imp Docs/Project/portF/node_modules/vue-writer/dist/vue-writer.ssr.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/vue-writer` if it exists or add a new declaration (.d.ts) file containing `declare module 'vue-writer';`Vetur(7016)

**To Reproduce**
1. create any vue3 project
2. npm install vue-writer
3. import using given commands(you'll see 3 dots under the 'vue-writer' text in the import command)
4. hover over the dots you'll get this
5. try running npm i --save-dev @types/vue-writer you'll get this in terminal :
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@types%2fvue-writer - Not found
npm ERR! 404
npm ERR! 404  '@types/vue-writer@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Expected behavior**
I am new to vue3 so if I am mistaken please guide me otherwise I think this module should get imported and everything should work fine.

**Desktop:**
 - OS: Windows10
 - Browser : Chorme
 - Version : VueJS 3
 - Using VS Code

**Comment by bkawakami** [comment]
Happen with me

**Comment by u-sour** [comment]
hi, did you fix this problem ?
