### ISSUE TITLE
Missing typings

### ISSUE THREAD

**Issue by jas777** [quelchx/vue-writer#7]
**Is your feature request related to a problem? Please describe.**
Yes, the lack of TypeScript typings makes working with ESLint harder

**Describe the solution you'd like**
I'm asking you to provide a @types/vue-writer package or include typings in the current one

**Describe alternatives you've considered**
...

**Additional context**
...

**Comment by quelchx** [comment]
This project was made using only Javascript so converting to Typescript isn't something I intend to do in the near future. It's a possibility, but not a feature I intend to implement at this time being. You can always create a custom module for your specific use case.

**Comment by quelchx** [comment]
For a quick work around I recommend trying something like so:
In the main directory of your application, create a file and name `vue-writer.d.ts` and add the following script
```ts
declare module "*vue-writer" {
  const content: any;
  export default content;
}
```

I know this isn't ideal, but it could work as a temporary workaround and shouldn't throw any linter errors. Good luck and let me know if this helps 👍
